### PR TITLE
deleted navheader home element

### PR DESCRIPTION
**Pull request by Ingi-Hong**
As per zeplin design 

https://trello.com/c/QuWl5iZ2/67-get-rid-of-home-tab

### CODE REVIEW

**Review by IanSaucy — CHANGES_REQUESTED** [review]
Overall good, can you remove these lines too?

https://github.com/UncountedDeaths/UncountedDeaths.github.io/blob/react_transfer/src/components/NavHeader.tsx#L95-L96

**Comment by Ingi-Hong** [comment]
> Overall good, can you remove these lines too?
> 
> https://github.com/UncountedDeaths/UncountedDeaths.github.io/blob/react_transfer/src/components/NavHeader.tsx#L95-L96

Those need to stay for functionality reasons. Don't know why but website breaks if I remove those. (specifically for navigating using the CEID logo)

**Comment by toucham** [comment]
> > Overall good, can you remove these lines too?
> > https://github.com/UncountedDeaths/UncountedDeaths.github.io/blob/react_transfer/src/components/NavHeader.tsx#L95-L96
> 
> Those need to stay for functionality reasons. Don't know why but website breaks if I remove those. (specifically for navigating using the CEID logo)

Screen Shot 2022-04-24 at 16 41 27
Screen Shot 2022-04-24 at 16 42 48

I think it got to do with the `selected` state and `key` of the route. I think you got to change those.

**Comment by IanSaucy** [comment]
Oh yikes, I guess something is depending on that route setState function which is really not great. We should probably just write a hook for handling route changes/checking the current route.

**Review by IanSaucy — APPROVED** [review]
lgtm

**Pull request merged**
