### PR TITLE
Fix styling in home page

### PR DESCRIPTION
**Pull request by toucham**
**Changes:**
- fix alignment of overlay text
- fix underline element under "Millions" so that it will always be under "Millions"
- fix alignment of image in `ContentCard` component

### CODE REVIEW

**Comment by IanSaucy** [comment]
Something weird is happening with the Menu at some, but not all screen widths. See here:

image

**Comment by toucham** [comment]
> Something weird is happening with the Menu at some, but not all screen widths. See here:
> 
> image

@IanSaucy fixed headers

**Comment by IanSaucy** [comment]
It looks like the menu items are not right aligned anymore. They also space evenly instead of staying "together" which makes it behave strangely on wider screens.

**Comment by IanSaucy** [comment]
I'm going to merge this since it has so many changes that affect other PRs. I created a bug for it in trello to get it resolved

**Pull request merged**
